In [1]:
#Importing numpy data set 
import numpy as np

In [5]:
#Checking which version of numpy we are using 
np.__version__

In [19]:
#creating alist of 6 numbers, list name = L
L = list(range(6))
L #Checking how L looks



[int, int, int, int, int, int]

In [ ]:
[type (item) for item in L] #Looking at list all items

In [20]:
R = [str(c) for c in L] #Doing list comprehension
R #Print R

['0', '1', '2', '3', '4', '5']

In [21]:
[type (item) for item in L] #Looking at list all items

[int, int, int, int, int, int]

In [23]:
#Numpy are homogenous unlike pandas
#Creating arrays in numpy
np.zeros(5, dtype='int')


array([0, 0, 0, 0, 0])

In [29]:
#creating a 2 row x 7 column matrix
np.ones((2,7), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [30]:
#Creating a maxtrix with predefined values
np.full((4,2),171206.23)

array([[ 171206.23,  171206.23],
       [ 171206.23,  171206.23],
       [ 171206.23,  171206.23],
       [ 171206.23,  171206.23]])

In [32]:
#create an array with a set sequence
np.arange(0, 30, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [45]:
#create an array of even space between the given range of values
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [48]:
#create a 2x3 array with mean 0 and standard deviation 1 in a given dimension
np.random.normal(0, 1, (3,2))

array([[-1.5641101 ,  0.08923252],
       [-1.12057662, -0.16924843],
       [ 0.56643101,  1.12564889]])

In [51]:
#Creating an identity matrix in numpy
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [76]:
#Set a random seed
np.random.seed(12)


In [77]:
x3 = np.random.randint(12, size=(1,2,3)) #three dimension





In [78]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim: 3
x3 shape: (1, 2, 3)
x3 size:  6


In [80]:
#Indexing arrays
R = np.array([1,2,3,4,5,6,7,8,9])
print(R)

[1 2 3 4 5 6 7 8 9]


In [81]:
R[0] #Assess the 0 value

1

In [82]:
R[6] #Assess the value 6

7

In [83]:
R[2:6] #Assess the value 6

array([3, 4, 5, 6])

In [92]:
R[-1] #Assess the value -1

array([7, 8])

In [94]:
R[-8:-2] #Assess the value -8 to -2

array([2, 3, 4, 5, 6, 7])

In [102]:
#Creating a mutidimensional array
R = np.random.normal(0, 1000, (4,3))
R 

array([[  138.48346081, -1083.21442202,   344.34272512],
       [  868.15752449, -1931.83025581, -1475.86643535],
       [ -694.64900389,   839.04331768,  -868.08898809],
       [  419.57749403,   242.62652647,  -592.12739525]])

In [104]:
R[1,2] #For 2nd row, 3rd column

-1475.8664353475097

In [107]:
#Replacing the value at 0,0 index
R[0,0] = 5
R

array([[    5.        , -1083.21442202,   344.34272512],
       [  868.15752449, -1931.83025581, -1475.86643535],
       [ -694.64900389,   839.04331768,  -868.08898809],
       [  419.57749403,   242.62652647,  -592.12739525]])